CREATE DATABASE IF NOT EXISTS buy_point CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE buy_point;
CREATE TABLE IF NOT EXISTS usuarios (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(120) NOT NULL,usuario VARCHAR(60) NOT NULL UNIQUE,
 email VARCHAR(160) NOT NULL UNIQUE,senha VARCHAR(255) NOT NULL,perfil ENUM('ADMIN','OPERADOR') NOT NULL DEFAULT 'OPERADOR',
 ativo TINYINT(1) NOT NULL DEFAULT 1,ultimo_login DATETIME NULL,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS produtos (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,codigo VARCHAR(60) NOT NULL UNIQUE,nome VARCHAR(180) NOT NULL,
 categoria VARCHAR(100) NULL,unidade VARCHAR(20) NOT NULL DEFAULT 'UN',preco DECIMAL(12,2) NOT NULL DEFAULT 0,
 estoque DECIMAL(12,3) NOT NULL DEFAULT 0,estoque_minimo DECIMAL(12,3) NOT NULL DEFAULT 0,ativo TINYINT(1) NOT NULL DEFAULT 1,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS movimentacoes_estoque (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,produto_id INT UNSIGNED NOT NULL,usuario_id INT UNSIGNED NULL,
 tipo ENUM('ENTRADA','SAIDA','AJUSTE') NOT NULL,quantidade DECIMAL(12,3) NOT NULL,observacao VARCHAR(255) NULL,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(produto_id) REFERENCES produtos(id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
 INDEX(produto_id),INDEX(criado_em)
) ENGINE=InnoDB;
INSERT INTO usuarios(nome,usuario,email,senha,perfil)
VALUES('Administrador','admin','admin@localhost','$2y$12$rhQq5w5pS4ugNSzLimj1A.lrGnhCIeGc0ypJtswLcNWi.b0tkSZ6S','ADMIN')
ON DUPLICATE KEY UPDATE usuario=usuario;
